image:
  repository: rancher/harvester-node-disk-manager
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

Debug: true
autoProvisionFilter: [/dev/sd*]
