name: Harvester-Node-Disk-Manager CI

# synchronize for pull request update
on:
  push:
    branches:
      - master
      - 'v**'
  pull_request:
    types: [opened, reopened, synchronize]

env:
  LIBVIRT_DEFAULT_URI: "qemu:///system"
  VM_DEPLOYED: false

jobs:
  validation:
    runs-on:
      - self-hosted
      - golang
    steps:
      - name: "Clone and check"
        uses: actions/checkout@v3
      - name: "Run validations"
        run: |
          make validate
          make validate-ci
  build:
    needs: validation
    runs-on:
      - self-hosted
      - golang
    steps:
      - name: "Local Build for next stage"
        run: |
          BUILD_FOR_CI=true make
          ./ci/scripts/patch-ttl-repo.sh
          echo "NDM override result as below:"
          cat ci/charts/ndm-override.yaml
  main_jobs:
    needs: build
    runs-on:
      - self-hosted
      - golang
    steps:
      - name: "Local Deployment (Harvester+Longhorn+Node-Disk-Manager) for testing"
        run: |
<<<<<<< HEAD
          rm -rf ndm-vagrant-rancherd
          git clone https://github.com/harvester/vagrant-rancherd ndm-vagrant-rancherd
          pushd ndm-vagrant-rancherd
          ./new_cluster.sh
          yq e -i ".longhorn_version = \"1.5.3\"" settings.yaml
=======
          rm -rf ndm-vagrant-k3s
          git clone https://github.com/bk201/vagrant-k3s ndm-vagrant-k3s
          pushd ndm-vagrant-k3s
          yq e -i ".cluster_size = 1" settings.yaml
          ./new-cluster.sh
          echo "VM_DEPLOYED=true" >> "$GITHUB_ENV"
          yq e -i ".longhorn_version = \"1.7.1\"" settings.yaml
>>>>>>> 78e0d91 (ci: make sure the if-condition works)
          ./scripts/deploy_longhorn.sh
          cp ../ci/scripts/deploy_ndm.sh ./deploy_ndm.sh
          ./deploy_ndm.sh
          popd
      - name: "Add disk"
        run: |
          pushd ndm-vagrant-rancherd
          ./scripts/attach-disk.sh node1
          sleep 30
          popd
      - name: "Patch Image target (for upgrade)"
        run: |
          ./ci/scripts/patch-ttl-repo.sh
          echo "NDM override result as below:"
          cat ci/charts/ndm-override.yaml 
      - name: "Upgrade NDM"
        run: |
          pushd ndm-vagrant-rancherd
          cp ../ci/scripts/upgrade_ndm.sh ./upgrade_ndm.sh
          ./upgrade_ndm.sh
          popd
      - name: "Run Basic Test"
        id: basic-test
        run: |
          pushd ndm-vagrant-rancherd
          vagrant ssh-config node1 > ../ssh-config
          cp kubeconfig ../kubeconfig
          popd
          echo Running integration tests
          NDM_HOME=`pwd` go test -v ./tests/...
      - name: "Get NDM logs"
        if: always()
        run: |
          if [ ${{ env.VM_DEPLOYED }} != 'true' ]; then
            echo "VM is not deployed, skip getting logs"
            exit 0
          fi
          ./ci/scripts/get-debug-info.sh
      - name: "Tear Down / Cleanup"
        if: always()
        run: |
<<<<<<< HEAD
          pushd ndm-vagrant-rancherd
=======
          if [ ${{ env.VM_DEPLOYED }} != 'true' ]; then
            echo "VM is not deployed, skip VM destroy"
            exit 0
          fi
          pushd ndm-vagrant-k3s
>>>>>>> 78e0d91 (ci: make sure the if-condition works)
          vagrant destroy -f --parallel
          popd
