name: Dev Build and Publish

on:
  push:
    branches:
    - master

jobs:
  build-for-dev:
    uses: ./.github/workflows/factory.yaml
    with:
      tag: ${{ github.ref_name }}-head
      push: true
    secrets: inherit